### ISSUE TITLE
Realtime Database Rules

### ISSUE THREAD

**Issue by albiols** [aashishpeepra/RestaurantReactApp#6]
Hi im trying to create another database on the Realtime Database but it wont work cause the rules aren't correct as i see.Can you please send me as screenshot of it or something.

**Comment by aashishpeepra** [comment]
{

  "rules": {

    ".read": "now < 1628879400000",  // 2021-8-14

    ".write": "now < 1628879400000",  // 2021-8-14

  }

}


Hey, you can try these firebase realtime rules for testing. change them for production.

**Comment by albiols** [comment]
thank you so much,i'll try them right now! 👍
